DamageEntity.ToxicGrenade = 5
DamageEntity.Molotov = 6
DamageEntity.Mine = 7
DamageEntity.Claymore = 8
DamageEntity.HEGrenade = 9
DamageEntity.LaserGrenade = 10
DamageEntity.Hunger = 11
DamageEntity.Thirst = 12
DamageEntity.VehicleGuard = 13
DamageEntity.WarpGrenade = 14
DamageEntity.Suicide = 15
DamageEntity.AdminKill = 16
DamageEntity.C4 = 17
DamageEntity.Food = 18
DamageEntity.MeleeGrapple = 19
DamageEntity.MeleeKick = 20
DamageEntity.MeleeSlidingKick = 21
DamageEntity.CruiseMissile = 22
DamageEntity.AreaBombing = 23
DamageEntity.TacticalNuke = 24
DamageEntity.CombatLog = 25
DamageEntity.DroneMachineGun = 25

DamageEntityNames = 
{
    [DamageEntity.None] = "None",
    [DamageEntity.Physics] = "Physics",
    [DamageEntity.Bullet] = "Bullet",
    [DamageEntity.Explosion] = "Explosion",
    [DamageEntity.Vehicle] = "Vehicle",
    [DamageEntity.ToxicGrenade] = "Toxic Grenade",
    [DamageEntity.Molotov] = "Molotov",
    [DamageEntity.Mine] = "Mine",
    [DamageEntity.Claymore] = "Claymore",
    [DamageEntity.HEGrenade] = "HE Grenade",
    [DamageEntity.LaserGrenade] = "Laser Grenade",
    [DamageEntity.Hunger] = "Hunger",
    [DamageEntity.Thirst] = "Thirst",
    [DamageEntity.VehicleGuard] = "Vehicle Guard",
    [DamageEntity.WarpGrenade] = "Warp Grenade",
    [DamageEntity.Suicide] = "Respawn",
    [DamageEntity.AdminKill] = "Admin Kill",
    [DamageEntity.C4] = "C4",
    [DamageEntity.Food] = "Food",
    [DamageEntity.MeleeGrapple] = "Grapplehook",
    [DamageEntity.MeleeKick] = "Melee Kick",
    [DamageEntity.MeleeSlidingKick] = "Melee Sliding Kick",
    [DamageEntity.CruiseMissile] = "Cruise Missile",
    [DamageEntity.AreaBombing] = "Area Bombing",
    [DamageEntity.TacticalNuke] = "Tactical Nuke",
    [DamageEntity.CombatLog] = "Combat Log",
    [DamageEntity.DroneMachineGun] = "Drone Machine Gun",
}