Items =  
{
    {
        name = "Apple",
        category = "Consumables",
        stacklimit = 5,
        loot = {1,2},
        rarity = 1,
        rarity_mod = {1,0.75}, -- Percent of original rarity (aka this * rarity)
        can_use = true,
        description = "An apple. Consuming it will restore hunger."
    },
    {
        name = "Grapplehook Upgrade - Speed",
        category = "General",
        stacklimit = 3,
        loot = {4,5,6},
        rarity = 0.2,
        rarity_mod = {1,1.25,1.5},
        can_equip = true,
        durable = true,
        max_durability = 800,
        max_loot = 1, -- Max number that can appear in a stack of loot
        equip_type = "grapple_upgrade",
        description = "An upgrade that can be applied to your grapplehook. Increases the speed at which you move when grappling. Equipping multiple will result in an even faster travel time."
    },
    {
        name = "Grapplehook Upgrade - Recharge",
        category = "General",
        stacklimit = 3,
        loot = {4,5,6},
        rarity = 0.18,
        rarity_mod = {1,1.25,1.5},
        can_equip = true,
        durable = true,
        max_durability = 500,
        max_loot = 1,
        equip_type = "grapple_upgrade",
        description = "An upgrade that can be applied to your grapplehook. Decreases the time that it takes to generate a grapplehook use. Equipping multiple will result in an even smaller recharge time."
    },
    {
        name = "Grapplehook Upgrade - Range",
        category = "General",
        stacklimit = 3,
        loot = {4,5,6},
        rarity = 0.15,
        rarity_mod = {1,1.25,1.75},
        can_equip = true,
        durable = true,
        max_durability = 1000,
        max_loot = 1,
        equip_type = "grapple_upgrade",
        description = "An upgrade that can be applied to your grapplehook. Increases the maximum range at which you can grapple. Equipping multiple will result in an even longer range."
    },
    {
        name = "Grapplehook Upgrade - Underwater",
        category = "General",
        stacklimit = 3,
        loot = {4,5,6},
        rarity = 0.15,
        rarity_mod = {1,1.25,1.5},
        can_equip = true,
        max_loot = 1,
        durable = true,
        equip_type = "grapple_upgrade",
        description = "An upgrade that can be applied to your grapplehook. Allows you to use your grapplehook underwater."
    },
    {
        name = "Grapplehook Upgrade - Gun",
        category = "General",
        stacklimit = 3,
        loot = {4,5,6},
        rarity = 0.125,
        rarity_mod = {1,1.25,1.5},
        can_equip = true,
        max_loot = 1,
        durable = true,
        equip_type = "grapple_upgrade",
        description = "An upgrade that can be applied to your grapplehook. Fires a missile from your grapplehook when used. Equipping multiple will result in a better missile."
    },
    {
        name = "Grapplehook Upgrade - Impulse",
        category = "General",
        stacklimit = 3,
        loot = {4,5,6},
        rarity = 0.17,
        rarity_mod = {1,1.25,1.5},
        can_equip = true,
        max_loot = 1,
        durable = true,
        equip_type = "grapple_upgrade",
        description = "An upgrade that can be applied to your grapplehook. Adds a small shockwave that emits from you after grappling. Equipping multiple will result in a more powerful shockwave."
    },
    {
        name = "Grapplehook Upgrade - Smart",
        category = "General",
        stacklimit = 3,
        loot = {4,5,6},
        rarity = 0.14,
        rarity_mod = {1,1.25,1.5},
        can_equip = true,
        max_loot = 1,
        max_durability = 300,
        durable = true,
        equip_type = "grapple_upgrade",
        description = "An upgrade that can be applied to your grapplehook. Makes your grapplehook hook onto objects even if you aren't looking directly at them. (JC3 style)"
    },
    {
        name = "Parachute",
        category = "General",
        stacklimit = 2,
        loot = {4,5,6},
        rarity = 0.1,
        rarity_mod = {1,1.5,2},
        can_equip = true,
        max_loot = 1,
        durable = true,
        max_durability = 1000,
        equip_type = "parachute",
        description = "The classic parachute. When equipped, it allows you to open your parachute."
    },
    {
        name = "Wingsuit",
        category = "Clothing",
        stacklimit = 1,
        loot = {6},
        rarity = 0.1,
        rarity_mod = {1},
        can_equip = true,
        max_loot = 1,
        durable = true,
        equip_type = "wingsuit",
        description = "A wingsuit. Allows you to glide over long distances easily."
    },
    {
        name = "Water Bottle",
        category = "Consumables",
        stacklimit = 3,
        loot = {1,2},
        rarity = 1,
        rarity_mod = {1,0.75},
        can_use = true,
        description = "A bottle of water. Restores thirst."
    },
    {
        name = "CamelBak",
        category = "Consumables",
        stacklimit = 1,
        loot = {2,3},
        rarity = 0.2,
        rarity_mod = {0.25,1},
        can_use = true,
        durable = true,
        description = "A hydration backpack. Restores some thirst every use."
    },
    {
        name = "Soda",
        category = "Consumables",
        stacklimit = 10,
        loot = {1,2},
        rarity = 0.75,
        rarity_mod = {0.8,1},
        can_use = true,
        description = "Generic soda. Restores thirst."
    },
    {
        name = "Granola Bar",
        category = "Consumables",
        stacklimit = 12,
        loot = {1,2},
        rarity = 1,
        rarity_mod = {1,0.5},
        can_use = true,
        description = "A granola bar. Restores hunger."
    },
    {
        name = "Trail Mix",
        category = "Consumables",
        stacklimit = 10,
        loot = {2},
        rarity = 0.5,
        rarity_mod = {1},
        can_use = true,
        description = "A bag of trail mix. Restores hunger."
    },
    {
        name = "Rations",
        category = "Consumables",
        stacklimit = 10,
        loot = {2,3},
        rarity = 0.2,
        rarity_mod = {0.5,1},
        can_use = true,
        description = "A box of various prepackaged food items. Restores hunger and thirst."
    },
    {
        name = "Scrap Metal",
        category = "Consumables",
        stacklimit = 25,
        loot = {1,2,3,4,5,6},
        rarity = 0.001,
        rarity_mod = {0.1,0.2,0.3,0.4,0.5,0.6},
        can_use = true,
        description = "A piece of scrap metal. Yummy, right?\n\nThis is an inside joke that stemmed from our first survival server, Fallen Civilization. People would find tons much scrap metal (which was basically useless). Someone asked if they could eat scrap metal, so now you can. Enjoy. Restores hunger and thirst fully."
    },
    {
        name = "Radiation Pills",
        category = "Consumables",
        stacklimit = 6,
        loot = {2,3},
        rarity = 0.4,
        rarity_mod = {0.25,1},
        can_use = true,
        description = "A bottle of pills that can lessen the effects of radiation."
    },
    {
        name = "Portal Gun",
        category = "Weapons",
        stacklimit = 1,
        loot = {6},
        rarity = 0.001,
        rarity_mod = {1},
        can_equip = true,
        durable = true,
        equip_type = "weapon",
        description = "A portal gun. Hold right click to shoot one portal, and hold left click to shoot another portal. Jumping into one portal will teleport you out the other. Requires Energy Cartridges to use."
    },
    {
        name = "Pistol",
        category = "Weapons",
        stacklimit = 2,
        loot = {1,2},
        rarity = 0.25,
        rarity_mod = {0.25,1},
        can_equip = true,
        durable = true,
        equip_type = "weapon",
        description = "The classic pistol."
    },
    {
        name = "Revolver",
        category = "Weapons",
        stacklimit = 2,
        loot = {1,2},
        rarity = 0.25,
        rarity_mod = {0.3,1},
        can_equip = true,
        durable = true,
        equip_type = "weapon",
        description = "The classic revolver."
    },
    {
        name = "Assault Rifle",
        category = "Weapons",
        stacklimit = 1,
        loot = {3,4},
        rarity = 0.15,
        rarity_mod = {0.5,1},
        can_equip = true,
        durable = true,
        equip_type = "weapon",
        description = "The classic assault rifle."
    },
    {
        name = "Sniper Rifle",
        category = "Weapons",
        stacklimit = 1,
        loot = {5,6},
        rarity = 0.1,
        rarity_mod = {0.5,1},
        can_equip = true,
        durable = true,
        equip_type = "weapon",
        description = "The classic sniper rifle."
    },
    {
        name = "Rocket Launcher",
        category = "Weapons",
        stacklimit = 1,
        loot = {6},
        rarity = 0.025,
        rarity_mod = {1},
        can_equip = true,
        durable = true,
        equip_type = "weapon",
        description = "The classic rocket launcher."
    },
    {
        name = "Submachine Gun",
        category = "Weapons",
        stacklimit = 2,
        loot = {2,3},
        rarity = 0.25,
        rarity_mod = {0.25,0.5},
        can_equip = true,
        durable = true,
        equip_type = "weapon",
        description = "The classic SMG."
    },
    {
        name = "Bubble Gun",
        category = "Weapons",
        stacklimit = 2,
        loot = {2,3},
        rarity = 0.1,
        rarity_mod = {0.5,1},
        can_equip = true,
        durable = true,
        equip_type = "weapon",
        description = "The classic bubble gun. Heals anyone you shoot."
    },
    {
        name = "Grenade Launcher",
        category = "Weapons",
        stacklimit = 2,
        loot = {3,4,5,6},
        rarity = 0.1,
        rarity_mod = {0.25,0.5,0.75,1},
        can_equip = true,
        durable = true,
        equip_type = "weapon",
        description = "The classic grenade launcher."
    },
    {
        name = "Shotgun",
        category = "Weapons",
        stacklimit = 1,
        loot = {3,4,5,6},
        rarity = 0.25,
        rarity_mod = {0.2,0.5,0.75,1},
        can_equip = true,
        durable = true,
        equip_type = "weapon",
        description = "The classic two-handed shotgun."
    },
    {
        name = "Sawn-Off Shotgun",
        category = "Weapons",
        stacklimit = 2,
        loot = {2,3},
        rarity = 0.3,
        rarity_mod = {0.5,1},
        can_equip = true,
        durable = true,
        equip_type = "weapon",
        description = "The classic one-handed shotgun."
    },
    {
        name = "Machine Gun",
        category = "Weapons",
        stacklimit = 1,
        loot = {3,4,5,6},
        rarity = 0.15,
        rarity_mod = {0.2,0.5,0.75,1},
        can_equip = true,
        durable = true,
        equip_type = "weapon",
        description = "The classic machine gun."
    },
    {
        name = "Assault Ammo",
        category = "Ammo",
        stacklimit = 100,
        loot = {2,3},
        rarity = 0.6,
        rarity_mod = {0.25,1},
        description = "Ammo for an Assault Rifle."
    },
    {
        name = "Energy Cartridge",
        category = "Ammo",
        stacklimit = 25,
        loot = {5,6},
        rarity = 0.25,
        rarity_mod = {0.75,1},
        max_loot = 3,
        description = "Used to power a Portal Gun. Each Energy Cartridge allows for one shot."
    },
    {
        name = "Pistol Ammo",
        category = "Ammo",
        stacklimit = 50,
        loot = {1,2},
        rarity = 0.6,
        rarity_mod = {0.75,1},
        description = "Ammo for a Pistol."
    },
    {
        name = "Revolver Ammo",
        category = "Ammo",
        stacklimit = 50,
        loot = {1,2},
        rarity = 0.6,
        rarity_mod = {0.75,1},
        description = "Ammo for a Revolver."
    },
    {
        name = "Sniper Ammo",
        category = "Ammo",
        stacklimit = 50,
        loot = {3,4},
        rarity = 0.25,
        rarity_mod = {0.5,1},
        description = "Ammo for a Sniper."
    },
    {
        name = "Sawn-Off Ammo",
        category = "Ammo",
        stacklimit = 50,
        loot = {1,2},
        rarity = 0.4,
        rarity_mod = {0.5,1},
        description = "Ammo for a Sawn-Off Shotgun."
    },
    {
        name = "Machine Gun Ammo",
        category = "Ammo",
        stacklimit = 50,
        loot = {2,3},
        rarity = 0.3,
        rarity_mod = {0.4,1},
        description = "Ammo for a Machine Gun."
    },
    {
        name = "Shotgun Ammo",
        category = "Ammo",
        stacklimit = 50,
        loot = {2,3},
        rarity = 0.4,
        rarity_mod = {0.5,1},
        description = "Ammo for a Shotgun."
    },
    {
        name = "Bubbles",
        category = "Ammo",
        stacklimit = 50,
        loot = {1,2},
        rarity = 0.3,
        rarity_mod = {0.5,1},
        description = "Ammo for a Bubble Gun. pew pew"
    },
    {
        name = "Submachine Gun Ammo",
        category = "Ammo",
        stacklimit = 50,
        loot = {1,2},
        rarity = 0.5,
        rarity_mod = {0.5,1},
        description = "Ammo for a Submachine Gun."
    },
    {
        name = "Rockets",
        category = "Ammo",
        stacklimit = 50,
        loot = {4,5,6},
        rarity = 0.12,
        rarity_mod = {0.5,0.75,1.5},
        max_loot = 3,
        description = "Ammo for a Rocket Launcher."
    },
    {
        name = "Grenade Munitions",
        category = "Ammo",
        stacklimit = 50,
        loot = {3,4},
        rarity = 0.2,
        rarity_mod = {0.5,1},
        description = "Ammo for a Grenade Launcher."
    },
    {
        name = "Rift Generator",
        category = "General",
        stacklimit = 1,
        loot = {4,5,6},
        rarity = 0.25,
        rarity_mod = {0.5,0.75,1},
        description = "Generates a temporary rift in front of you."
    },
    {
        name = "Car Paint",
        category = "General",
        stacklimit = 3,
        loot = {2,3},
        rarity = 0.3,
        rarity_mod = {0.5,1},
        description = "Used to paint your car different colors."
    },
    {
        name = "Guardian Tank Armor", -- armor with a ton of durability
        category = "Clothing",
        stacklimit = 1,
        loot = {5},
        rarity = 0.01,
        rarity_mod = {1},
        can_equip = true,
        durable = true,
        max_durability = 5000,
        equip_type = "chest",
        description = "A piece of casing from an ancient, age-old automaton. This makes a rough, yet extremely durable piece of armor."
    },
    {
        name = "Grid Armor MKI", -- yellow outline, yellow streak, disable collision
        category = "Clothing",
        stacklimit = 1,
        loot = {5},
        rarity = 0.005,
        rarity_mod = {1},
        can_equip = true,
        durable = true,
        max_durability = 500,
        equip_type = "full_protection",
        description = "When worn, this temporarily creates a Multi-Spatial Phasing Beacon, which enables the user to exist both in Gridspace and the real world at the same time. The appearance of the user when in this form has lead to this device being called 'grid armor'. When being worn, the user evades most attacks, yet can still interact with the world as normal."
    },
    {
        name = "Grid Armor MKII", -- orange outline, *1.25 speed, orange streak, disable collision
        category = "Clothing",
        stacklimit = 1,
        loot = {},
        rarity = 1,
        rarity_mod = {},
        can_equip = true,
        durable = true,
        max_durability = 1000,
        equip_type = "full_protection",
        description = "When worn, this temporarily creates a Multi-Spatial Phasing Beacon, which enables the user to exist both in Gridspace and the real world at the same time. The appearance of the user when in this form has lead to this device being called 'grid armor'. When being worn, the user evades most attacks, yet can still interact with the world as normal."
    },
    {
        name = "Grid Armor MKIII", -- red outline, * 1.5 speed, red streak, disable collision
        category = "Clothing",
        stacklimit = 1,
        loot = {},
        rarity = 1,
        rarity_mod = {},
        can_equip = true,
        durable = true,
        max_durability = 1500,
        equip_type = "full_protection",
        description = "When worn, this temporarily creates a Multi-Spatial Phasing Beacon, which enables the user to exist both in Gridspace and the real world at the same time. The appearance of the user when in this form has lead to this device being called 'grid armor'. When being worn, the user evades most attacks, yet can still interact with the world as normal."
    },
    {
        name = "Grid Armor MKIV", -- blue outline, *2 speed, blue streak, invisible model, disable collision
        category = "Clothing",
        stacklimit = 1,
        loot = {},
        rarity = 1,
        rarity_mod = {},
        can_equip = true,
        durable = true,
        max_durability = 2000,
        equip_type = "full_protection",
        description = "When worn, this temporarily creates a Multi-Spatial Phasing Beacon, which enables the user to exist both in Gridspace and the real world at the same time. The appearance of the user when in this form has lead to this device being called 'grid armor'. When being worn, the user evades most attacks, yet can still interact with the world as normal."
    },
    {
        name = "Spatial Encoding Beacon", -- Teleports you to the grid (takes 30 seconds to use)
        category = "General",
        stacklimit = 3,
        loot = {4,5,6},
        can_use = true,
        rarity = 0.05,
        rarity_mod = {0.5,0.75,1},
        description = "This Spatial Encoding Beacon allows the user to encode their DNA sequence on the fly and teleport themselves into the Grid."
    },
    {
        name = "Mass Spatial Encoding Beacon", -- Teleports people around you to the grid (takes 45 seconds to use)
        category = "General",
        stacklimit = 1,
        loot = {5,6},
        can_use = true,
        rarity = 0.01,
        rarity_mod = {1.5,1},
        description = "This Mass Spatial Encoding Beacon allows the user and those around them to encode their DNA sequence on the fly and teleport themselves into the Grid."
    },
    {
        name = "EMP", -- Sets off a blast that disables all electronics within a range
        category = "Weapons",
        stacklimit = 3,
        loot = {4,5,6},
        can_use = true,
        rarity = 0.15,
        rarity_mod = {0.5,0.75,1},
        description = "Sets off a large electrical blast that disables electronics within range."
    },
    {
        name = "Radar",
        category = "General",
        stacklimit = 1,
        loot = {6},
        can_equip = true,
        equip_type = "radar",
        durable = true,
        rarity = 0.05,
        rarity_mod = {1},
        description = "When equipped, this item allows you see other nearby players on your minimap. Batteries required."
    },
    {
        name = "Batteries",
        category = "General",
        stacklimit = 6,
        loot = {2,3},
        durable = true,
        rarity = 0.2,
        rarity_mod = {0.25,1},
        description = "Used to power various electronic devices."
    },
    {
        name = "Unstable Boots", -- Run fast or something and you get thrown/teleported lol
        category = "General",
        stacklimit = 1,
        loot = {},
        durable = true,
        can_equip = true,
        equip_type = "boots",
        rarity = 1,
        rarity_mod = {},
        description = "Dark energy seeps from these boots. Wearing these for extended periods of time may induce strange side effects."
    },
    {
        name = "Unstable Serum", -- strange effects
        category = "Comsumables",
        stacklimit = 2,
        loot = {},
        can_use = true,
        rarity = 1,
        rarity_mod = {},
        description = "This is a vile of a deep, dark liquid. Ingesting this may induce strange side effects."
    },
    {
        name = "Credits", -- Currency
        category = "General",
        stacklimit = 500,
        loot = {}, -- Automatically placed in every lootbox for now
        rarity = 0,
        max_loot = 3,
        rarity_mod = {},
        description = "Currency. Used to buy/steal cars, craft items at Outposts, and purchase items from Black Market Dealers."
    },
    {
        name = "Red Spray Paint",
        category = "General",
        can_equip = true,
        durable = true,
        stacklimit = 3,
        loot = {2},
        rarity = 0.2,
        rarity_mod = {1},
        equip_type = "weapon",
        description = "Equip and start painting! You can paint on almost any surface."
    },
    {
        name = "Orange Spray Paint",
        category = "General",
        can_equip = true,
        durable = true,
        stacklimit = 3,
        loot = {2},
        rarity = 0.2,
        rarity_mod = {1},
        equip_type = "weapon",
        description = "Equip and start painting! You can paint on almost any surface."
    },
    {
        name = "Yellow Spray Paint",
        category = "General",
        can_equip = true,
        durable = true,
        stacklimit = 3,
        loot = {2},
        rarity = 0.2,
        rarity_mod = {1},
        equip_type = "weapon",
        description = "Equip and start painting! You can paint on almost any surface."
    },
    {
        name = "Green Spray Paint",
        category = "General",
        can_equip = true,
        durable = true,
        stacklimit = 3,
        loot = {2},
        rarity = 0.2,
        rarity_mod = {1},
        equip_type = "weapon",
        description = "Equip and start painting! You can paint on almost any surface."
    },
    {
        name = "Blue Spray Paint",
        category = "General",
        can_equip = true,
        durable = true,
        stacklimit = 3,
        loot = {2},
        rarity = 0.2,
        rarity_mod = {1},
        equip_type = "weapon",
        description = "Equip and start painting! You can paint on almost any surface."
    },
    {
        name = "Purple Spray Paint",
        category = "General",
        can_equip = true,
        durable = true,
        stacklimit = 3,
        loot = {2},
        rarity = 0.2,
        rarity_mod = {1},
        equip_type = "weapon",
        description = "Equip and start painting! You can paint on almost any surface."
    },
    {
        name = "Pink Spray Paint",
        category = "General",
        can_equip = true,
        durable = true,
        stacklimit = 3,
        loot = {2},
        rarity = 0.2,
        rarity_mod = {1},
        equip_type = "weapon",
        description = "Equip and start painting! You can paint on almost any surface."
    },
    {
        name = "White Spray Paint",
        category = "General",
        can_equip = true,
        durable = true,
        stacklimit = 3,
        loot = {2},
        rarity = 0.2,
        rarity_mod = {1},
        equip_type = "weapon",
        description = "Equip and start painting! You can paint on almost any surface."
    },
    {
        name = "Black Spray Paint",
        category = "General",
        can_equip = true,
        durable = true,
        stacklimit = 3,
        loot = {2},
        rarity = 0.2,
        rarity_mod = {1},
        equip_type = "weapon",
        description = "Equip and start painting! You can paint on almost any surface."
    },
    {
        name = "Spray Paint Remover",
        category = "General",
        can_equip = true,
        durable = true,
        stacklimit = 3,
        loot = {2},
        rarity = 0.1,
        rarity_mod = {1},
        equip_type = "weapon",
        description = "Equip and start removing Spray Paint!"
    },
    {
        name = "Medkit",
        category = "Consumables",
        can_use = true,
        stacklimit = 3,
        loot = {2,3},
        rarity = 0.3,
        rarity_mod = {1,0.5},
        description = "Restores 50% health when used."
    },
    {
        name = "Medpack",
        category = "Consumables",
        can_use = true,
        stacklimit = 3,
        loot = {2,3},
        rarity = 0.2,
        rarity_mod = {0.25,1},
        description = "Restores 100% health when used."
    },
    {
        name = "Beta Hat",
        category = "Clothing",
        can_equip = true,
        stacklimit = 3,
        loot = {},
        nodrop = true,
        rarity = 1,
        rarity_mod = {},
        equip_type = "hat",
        description = "A hat given to beta testers."
    },
    {
        name = "Alpha Hat",
        category = "Clothing",
        can_equip = true,
        stacklimit = 3,
        loot = {},
        nodrop = true,
        rarity = 1,
        rarity_mod = {},
        equip_type = "hat",
        description = "A hat given to alpha testers."
    },
    {
        name = "Landclaim",
        category = "Build",
        can_use = true,
        stacklimit = 1,
        loot = {4,5,6},
        rarity = 0.03,
        rarity_mod = {0.5,0.75,1},
        description = "Used to claim an area of land to prevent others from building on your turf. Also prevents structure decay."
    },
    {
        name = "Laser Glove", -- Shows a small beam going to a target location then fires a laser
        category = "Weapons",
        can_equip = true,
        durable = true,
        stacklimit = 1,
        loot = {},
        rarity = 1,
        rarity_mod = {},
        equip_type = "weapon_hand",
        description = "Click to equip, and then hold Q to use. Uses a small targeting beam and fires a laser shortly after."
    },
    {
        name = "Concussion Glove", -- Slams hand down on ground to create a shockwave
        category = "Weapons",
        can_equip = true,
        durable = true,
        stacklimit = 1,
        loot = {},
        rarity = 1,
        rarity_mod = {},
        equip_type = "weapon_hand",
        description = "Click to equip, and then press Q to use. The user slams their fist on the ground, creating a shockwave that knocks nearby players back."
    },
    {
        name = "Repair Hammer", -- Press Q to whack builds and repair them
        category = "Weapons",
        can_equip = true,
        durable = true,
        stacklimit = 1,
        loot = {4,5,6},
        rarity = 0.1,
        rarity_mod = {0.5,0.75,1},
        equip_type = "weapon_hand",
        description = "Click to equip, and then press Q to use. Use on buildings to repair them."
    },
    {
        name = "Death Drop Locator",
        category = "General",
        can_use = true,
        stacklimit = 3,
        loot = {4},
        rarity = 0.15,
        rarity_mod = {1},
        description = "After dying, you can use this item to place a waypoint on the location where you died."
    },
    {
        name = "Jump Pad",
        category = "Build",
        can_use = true,
        stacklimit = 3,
        loot = {3,4},
        rarity = 0.4,
        max_loot = 1,
        rarity_mod = {0.5,1},
        description = "This object will bounce you into the air when you step on it."
    },
    {
        name = "Nitro",
        category = "General",
        durable = true,
        stacklimit = 5,
        loot = {2,3},
        rarity = 0.2,
        max_loot = 1,
        rarity_mod = {0.5,1},
        description = "While in a vehicle, you can hold shift (land vehicles) or Q (for air vehicles) to boost."
    },
    {
        name = "Vehicle Repair Kit",
        category = "General",
        can_use = true,
        stacklimit = 3,
        loot = {2,3},
        rarity = 0.15,
        rarity_mod = {0.5,1},
        description = "Point at a vehicle to repair and use to repair the vehicle completely. There must be no one inside the vehicle."
    },
    {
        name = "Mine",
        category = "Weapons",
        can_use = true,
        stacklimit = 10,
        loot = {3,4,5,6},
        rarity = 0.4,
        max_loot = 2,
        rarity_mod = {0.25,1,1.25,1.5},
        description = "Use the item to place a mine. The mine will explode when someone who is not your friend walks over it."
    },
    {
        name = "Claymore",
        category = "Weapons",
        can_use = true,
        stacklimit = 10,
        loot = {3},
        rarity = 0.3,
        max_loot = 2,
        rarity_mod = {1},
        description = "Use the item to place a claymore. This can be detonated remotely by holding right click or activated using a Tripwire."
    },
    {
        name = "Tripwire",
        category = "General",
        can_equip = true,
        durable = true,
        stacklimit = 10,
        loot = {2,3},
        rarity = 0.25,
        max_loot = 2,
        rarity_mod = {0.5,1},
        equip_type = "weapon_hand",
        description = "Equip to begin placing Tripwire. Click to set pivot points, and right click to undo. Used to trigger various items, such as the Claymore. Tripwire can be destroyed if hit by an explosive blast."
    },
    {
        name = "Bouncing Betty",
        category = "Weapons",
        can_use = true,
        stacklimit = 10,
        loot = {3},
        rarity = 0.35,
        max_loot = 2,
        rarity_mod = {1},
        description = "Use the item to place it. When someone who is not your friend walks near it, it will jump up and explode after a small delay."
    },
    {
        name = "Stun Grenade",
        category = "Weapons",
        can_equip = true,
        stacklimit = 10,
        loot = {2,3},
        rarity = 0.5,
        max_loot = 2,
        rarity_mod = {0.5,1},
        equip_type = "thrown",
        description = "Click to equip, and then hold V to adjust throw strength and release to throw. This grenade blinds and disorients nearby players for a short time."
    },
    {
        name = "Impulse Grenade",
        category = "Weapons",
        can_equip = true,
        stacklimit = 10,
        loot = {2,3},
        rarity = 0.5,
        max_loot = 2,
        rarity_mod = {0.5,1},
        equip_type = "thrown",
        description = "Click to equip, and then hold V to adjust throw strength and release to throw. This grenade sends out a shockwave that knocks back nearby players."
    },
    {
        name = "Concussion Grenade",
        category = "Weapons",
        can_equip = true,
        stacklimit = 10,
        loot = {2,3},
        rarity = 0.5,
        rarity_mod = {0.5,1},
        max_loot = 2,
        equip_type = "thrown",
        description = "Click to equip, and then hold V to adjust throw strength and release to throw. This grenade sets of a small, yet powerful blast."
    },
    {
        name = "Smoke Grenade",
        category = "Weapons",
        can_equip = true,
        stacklimit = 10,
        loot = {2,3},
        rarity = 0.6,
        max_loot = 3,
        rarity_mod = {0.5,1},
        equip_type = "thrown",
        description = "Click to equip, and then hold V to adjust throw strength and release to throw. This grenade fills a large area with smoke."
    },
    {
        name = "Toxic Grenade",
        category = "Weapons",
        can_equip = true,
        stacklimit = 10,
        loot = {2,3},
        rarity = 0.4,
        rarity_mod = {0.5,1},
        max_loot = 2,
        equip_type = "thrown",
        description = "Click to equip, and then hold V to adjust throw strength and release to throw. This grenade creates a cloud of toxic gas that lasts for a little while."
    },
    {
        name = "EMP Grenade",
        category = "Weapons",
        can_equip = true,
        stacklimit = 10,
        loot = {3,4},
        rarity = 0.3,
        rarity_mod = {0.5,1},
        max_loot = 1,
        equip_type = "thrown",
        description = "Click to equip, and then hold V to adjust throw strength and release to throw. This grenade releases an electrical surge when it explodes, disabling all nearby electronics."
    },
    {
        name = "Anti-Tank Grenade",
        category = "Weapons",
        can_equip = true,
        stacklimit = 10,
        loot = {3,4},
        rarity = 0.25,
        rarity_mod = {0.5,1},
        max_loot = 1,
        equip_type = "thrown",
        description = "Click to equip, and then hold V to adjust throw strength and release to throw. This grenade is best used against tanks."
    },
    {
        name = "Warp Grenade",
        category = "Weapons",
        can_equip = true,
        stacklimit = 10,
        loot = {4,5,6},
        rarity = 0.1,
        rarity_mod = {0.5,0.75,1},
        max_loot = 1,
        equip_type = "thrown",
        description = "Click to equip, and then hold V to adjust throw strength and release to throw. After a short delay, you will be teleported to the grenade's position."
    },
    {
        name = "Incendiary Grenade",
        category = "Weapons",
        can_equip = true,
        stacklimit = 10,
        loot = {2,3},
        rarity = 0.4,
        rarity_mod = {0.5,1},
        max_loot = 2,
        equip_type = "thrown",
        description = "Click to equip, and then hold V to adjust throw strength and release to throw. This grenade produces intense heat for a while."
    },
    {
        name = "Fragmentation Grenade",
        category = "Weapons",
        can_equip = true,
        stacklimit = 10,
        loot = {2,3},
        rarity = 0.65,
        max_loot = 2,
        rarity_mod = {0.5,1},
        equip_type = "thrown",
        description = "Click to equip, and then hold V to adjust throw strength and release to throw. This grenade releases lethal fragments that damage nearby players."
    },
    {
        name = "Molotov Cocktail",
        category = "Weapons",
        can_equip = true,
        stacklimit = 10,
        loot = {2,3},
        rarity = 0.4,
        rarity_mod = {0.5,1},
        max_loot = 2,
        equip_type = "thrown",
        description = "Click to equip, and then hold V to adjust throw strength and release to throw. It sets a small area on fire for a little while."
    },
    {
        name = "Guided Missile",
        category = "Weapons",
        can_use = true,
        stacklimit = 5,
        loot = {3,4,5,6},
        rarity = 0.3,
        rarity_mod = {0.25,0.5,0.75,1},
        max_loot = 1,
        description = "Aftere a brief delay, a jet will fire a missile from high in the sky towards your location. You can control the direction and speed of this missile."
    },
    {
        name = "Airstrike",
        category = "Weapons",
        can_use = true,
        stacklimit = 3,
        loot = {4,5,6},
        rarity = 0.3,
        rarity_mod = {0.5,0.75,1},
        max_loot = 1,
        description = "Look at the location you would like an Airstrike to target. After a delay, a jet will fly by and drop bombs on the location."
    },
    {
        name = "Area Bombardment",
        category = "Weapons",
        can_use = true,
        stacklimit = 2,
        loot = {4,5,6},
        rarity = 0.15,
        rarity_mod = {0.5,0.75,1},
        description = "Look at the location you would like an Area Bombardment to target. After a delay, jets will drop a number of bombs in the area."
    },
    {
        name = "Nuke",
        category = "Weapons",
        can_use = true,
        stacklimit = 2,
        loot = {4,5,6},
        rarity = 0.15,
        rarity_mod = {0.5,0.75,1},
        description = "Look at the location you would like a Nuke to strike. After a large delay, a massive explosion will occur in the target area. A radiation zone will be left behind for a little while afterwards."
    },
    {
        name = "C4",
        category = "Weapons",
        can_use = true,
        stacklimit = 10,
        loot = {4,5,6},
        rarity = 0.25,
        rarity_mod = {0.5,0.75,1},
        max_loot = 2,
        description = "A placeable explosive. Look at the location you want to place it at and use the item. Hold right click to detonate all placed C4. Can be used to destroy buildings placed by other players."
    },
    {
        name = "Call Air Support",
        category = "Weapons",
        can_use = true,
        stacklimit = 1,
        loot = {5,6},
        rarity = 0.2,
        rarity_mod = {2,1},
        description = "Use to call in helicopter air support."
    },
    {
        name = "Woet",
        category = "General",
        can_use = true,
        stacklimit = 5,
        loot = {3},
        rarity = 0.2,
        rarity_mod = {1},
        max_loot = 1,
        description = "Flips a vehicle 180 degrees. Useful if your car has flipped over."
    },
    {
        name = "Mine Detector",
        category = "General",
        can_equip = true,
        equip_type = "detector",
        durable = true,
        stacklimit = 2,
        loot = {4,5},
        rarity = 0.15,
        rarity_mod = {0.75,1},
        description = "Detects nearby mines. Batteries required."
    },
    {
        name = "WaterWalk Boots",
        category = "Clothing",
        can_equip = true,
        equip_type = "boots",
        durable = true,
        stacklimit = 1,
        loot = {5},
        rarity = 0.05,
        rarity_mod = {1},
        description = "When equipped, these boots allow you to walk on water. Be careful though, as the surface will be hard if you skydive into it."
    },
    {
        name = "Stash",
        category = "Build",
        can_use = true,
        stacklimit = 3,
        loot = {3,4},
        rarity = 0.1,
        rarity_mod = {0.5,1},
        max_loot = 1,
        description = "A container used to stash your items. Place it on the ground to set it up. Can be locked and improved using Stash Upgrades."
    },
    {
        name = "Stash Hacker",
        category = "General",
        can_use = true,
        stacklimit = 3,
        loot = {5,6},
        rarity = 0.025,
        rarity_mod = {0.5,1},
        max_loot = 1,
        description = "A device that can be used to hack into locked Stashes. Batteries required."
    },
    {
        name = "Stash Upgrade - Space",
        category = "General",
        can_use = true,
        stacklimit = 5,
        loot = {4,5,6},
        rarity = 0.2,
        rarity_mod = {0.5,1,0.75},
        max_loot = 1,
        description = "An upgrade that can be applied to your Stash. When applied, this add +1 space to your Stash."
    },
    {
        name = "Stash Upgrade - Keypad Lock",
        category = "General",
        can_use = true,
        stacklimit = 5,
        loot = {4,5,6},
        rarity = 0.15,
        rarity_mod = {0.5,1,1.5},
        max_loot = 1,
        description = "An upgrade that can be applied to your Stash. When applied, a code will have to be entered in order to open the Stash."
    },
    {
        name = "Stash Upgrade - Identity Lock",
        category = "General",
        can_use = true,
        stacklimit = 5,
        loot = {5,6},
        rarity = 0.02,
        rarity_mod = {1,1.5},
        max_loot = 1,
        description = "An upgrade that can be applied to your Stash. When applied, you can set the types of people that are allowed to access the Stash."
    },
    {
        name = "Stash Upgrade - Shield",
        category = "General",
        can_use = true,
        stacklimit = 5,
        loot = {4,5,6},
        rarity = 0.175,
        rarity_mod = {0.5,0.75,1},
        max_loot = 1,
        description = "An upgrade that can be applied to your Stash. When applied, this protects the Stash from some explosive damage."
    },
    {
        name = "Stash Upgrade - Hack Protection",
        category = "General",
        can_use = true,
        stacklimit = 5,
        loot = {4,5,6},
        rarity = 0.125,
        rarity_mod = {0.5,0.75,1},
        max_loot = 1,
        description = "An upgrade that can be applied to your Stash. When applied, this will block one hacking attempt."
    },
    {
        name = "Stash Upgrade - Electrocute",
        category = "General",
        can_use = true,
        stacklimit = 5,
        loot = {5,6},
        rarity = 0.1,
        rarity_mod = {1,0.75},
        max_loot = 1,
        description = "An upgrade that can be applied to your Stash. When applied, this will electrocute anyone who hacks into the Stash."
    },
    {
        name = "Stash Upgrade - Self-Destruct",
        category = "General",
        can_use = true,
        stacklimit = 5,
        loot = {4,5,6},
        rarity = 0.175,
        rarity_mod = {1,0.75,0.5},
        max_loot = 1,
        description = "An upgrade that can be applied to your Stash. When applied, the Stash will self-destruct and destroy all contents inside when hacked into. Will likely also kill the hacker."
    },
    {
        name = "Stash Upgrade - Notifier",
        category = "General",
        can_use = true,
        stacklimit = 5,
        loot = {5,6},
        rarity = 0.1,
        rarity_mod = {1,1.5},
        max_loot = 1,
        description = "An upgrade that can be applied to your Stash. When applied, the owner of the Stash will receive notifications when someone damages or tries to hack into the Stash."
    },
    {
        name = "Stash Upgrade - Invisibility",
        category = "General",
        can_use = true,
        stacklimit = 5,
        loot = {5,6},
        rarity = 0.01,
        rarity_mod = {0.5,1},
        max_loot = 1,
        description = "An upgrade that can be applied to your Stash. When applied, the Stash will become invisible."
    },
    {
        name = "Stash Finder",
        category = "General",
        can_equip = true,
        equip_type = "detector",
        durable = true,
        stacklimit = 1,
        loot = {5,6},
        rarity = 0.01,
        rarity_mod = {0.5,1},
        description = "A device that allows you to find invisible Stashes. When equipped, it will outline all nearby storages. Batteries required."
    },
    {
        name = "Wall",
        category = "Build",
        can_use = true,
        stacklimit = 20,
        loot = {3,4,6},
        rarity = 0.3,
        rarity_mod = {0.5,1,2},
        max_loot = 3,
        description = "A placeable wall. Use this to build bases. Right click it and choose Reinforce to use up walls from your inventory to make it stronger."
    },
    {
        name = "Bed",
        category = "Build",
        can_use = true,
        stacklimit = 1,
        loot = {4,5,6},
        rarity = 0.1,
        rarity_mod = {0.5,1,1.5},
        description = "A placeable bed. After placing, you can set your respawn position at its location by looking at it and pressing E."
    },
    {
        name = "Door",
        category = "Build",
        can_use = true,
        stacklimit = 1,
        loot = {5},
        rarity = 0.15,
        rarity_mod = {0.75,1,1.25},
        description = "A placeable door. You can configure who is allowed to open this door. Right click it and choose Reinforce to use up doors from your inventory to make it stronger."
    },
    {
        name = "Sign",
        category = "Build",
        can_use = true,
        stacklimit = 5,
        loot = {3,4},
        rarity = 0.15,
        rarity_mod = {0.5,1},
        max_loot = 1,
        description = "A placeable sign. After placing this, you can write on it."
    },
    {
        name = "Turret",
        category = "Build",
        can_use = true,
        stacklimit = 1,
        loot = {4,5,6},
        rarity = 0.025,
        rarity_mod = {0.5,0.75,1.5},
        description = "A placeable turret. The turret will shoot any enemies that come close."
    },
    {
        name = "Helipad",
        category = "Build",
        can_use = true,
        stacklimit = 1,
        loot = {4,5,6},
        rarity = 0.1,
        rarity_mod = {0.5,2,1},
        description = "A placeable helipad. Great for landing helicopters on."
    },
    {
        name = "Teleporter",
        category = "Build",
        can_use = true,
        stacklimit = 2,
        loot = {5,6},
        rarity = 0.05,
        rarity_mod = {1,2},
        description = "A placeable teleporter. After placing two teleporters, open their configurations with E and add each teleporter's ID to 'Allow TPs From'. This will link the teleporters and allow you to teleport between them. You can also disable incoming teleports with the configuration menu."
    },
    {
        name = "Cloaker",
        category = "Build",
        can_use = true,
        stacklimit = 1,
        loot = {5},
        rarity = 0.01,
        rarity_mod = {1},
        description = "A placeable device. After placing, this will cloak any nearby objects, players, and vehicles. These affected entities within range can only be seen when you are within 25m of them. Toggle on/off with the menu. Requires batteries to use."
    },
    {
        name = "Binoculars",
        category = "General",
        can_use = true,
        stacklimit = 2,
        loot = {3,4},
        rarity = 0.12,
        rarity_mod = {0.5,1},
        description = "A pair of binoculars. Use to peer through them. Zoom in/out with left and right click."
    },
    {
        name = "Helmet",
        category = "Clothing",
        can_equip = true,
        durable = true,
        equip_type = "hat",
        stacklimit = 3,
        loot = {2},
        rarity = 0.25,
        rarity_mod = {1},
        max_loot = 1,
        description = "A helmet that can be worn. Protects against damage from headshots."
    },
    {
        name = "Police Helmet",
        category = "Clothing",
        can_equip = true,
        durable = true,
        equip_type = "hat",
        stacklimit = 2,
        loot = {3},
        rarity = 0.25,
        rarity_mod = {1},
        description = "A military helmet that can be worn. Protects against damage from headshots."
    },
    {
        name = "Military Helmet",
        category = "Clothing",
        can_equip = true,
        durable = true,
        equip_type = "hat",
        stacklimit = 2,
        loot = {4},
        rarity = 0.2,
        rarity_mod = {1},
        description = "A military helmet that can be worn. Protects against damage from headshots."
    },
    {
        name = "Military Vest",
        category = "Clothing",
        can_equip = true,
        durable = true,
        equip_type = "chest",
        stacklimit = 1,
        loot = {3},
        rarity = 0.1,
        rarity_mod = {1},
        description = "A military vest that can be worn. Protects against damage from bodyshots."
    },
    {
        name = "Kevlar Vest",
        category = "Clothing",
        can_equip = true,
        durable = true,
        equip_type = "chest",
        stacklimit = 1,
        loot = {4,5,6},
        rarity = 0.1,
        rarity_mod = {0.5,1,1.5},
        description = "A military vest that can be worn. Protects against damage from all sources."
    },
    {
        name = "Mysterious Note",
        category = "General",
        can_use = true,
        stacklimit = 1,
        loot = {5},
        rarity = 0.2,
        rarity_mod = {1},
        description = "A mysterious note. Who knows what you may find if you follow it."
    },
    {
        name = "Burnt Note",
        category = "General",
        can_use = true,
        stacklimit = 1,
        loot = {5},
        rarity = 0.2,
        rarity_mod = {1},
        description = "A burnt note. Difficult to read, but it may be important."
    },
    {
        name = "Death Note",
        category = "General",
        can_use = true,
        stacklimit = 1,
        loot = {5},
        rarity = 0.2,
        rarity_mod = {1},
        description = "A death note. Nothing special to see here...or is there?"
    },
    {
        name = "WindWalker Potion",
        category = "Consumables",
        can_use = true,
        stacklimit = 3,
        loot = {5},
        rarity = 0.1,
        rarity_mod = {1},
        max_loot = 1,
        description = "Upon drinking this potion, your body is transformed into a smoke-like appearance. This allows you to fly for the duration of the potion, but you are unable to attack or use other items."
    },
    {
        name = "UAV",
        category = "General",
        can_use = true,
        stacklimit = 2,
        loot = {5,6},
        rarity = 0.15,
        rarity_mod = {1,0.5},
        max_loot = 1,
        description = "An unmanned aerial vehicle. This drone is excellent for scouting nearby areas and finding players with its built in Player Locator."
    },
    {
        name = "Laser Drill",
        category = "Weapons",
        can_use = true,
        stacklimit = 1,
        loot = {5,6},
        rarity = 0.025,
        rarity_mod = {0.5,1},
        max_loot = 1,
        description = "A frail yet powerful device that can be placed on the ground. Once placed, you can configure it to fire out laser beams that can pierce through buildings. Very effective at breaking into bases."
    },
    {
        name = "Sand Goggles", -- Only in loot in the desert
        category = "Clothing",
        can_equip = true,
        stacklimit = 1,
        durable = true,
        loot = {4},
        rarity = 0.05,
        rarity_mod = {1},
        max_loot = 1,
        equip_type = "glasses",
        description = "Really RADICAL goggles that protect your eyes from harsh sandstorms."
    },

}

Items_ammo_types = 
{
    ["Revolver"] = "Revolver Ammo",
    ["Pistol"] = "Pistol Ammo",
    ["Submachine Gun"] = "Submachine Gun Ammo",
    ["Sawn-Off Shotgun"] = "Sawn-Off Ammo",
    ["Machine Gun"] = "Machine Gun Ammo",
    ["Bubble Gun"] = "Bubbles",
    ["Grenade Launcher"] = "Grenade Munitions",
    ["Sniper Rifle"] = "Sniper Ammo",
    ["Rocket Launcher"] = "Rockets",
    ["Assault Rifle"] = "Assault Ammo",
    ["Shotgun"] = "Shotgun Ammo",
    ["Portal Gun"] = "Energy Cartridge"
    -- And more custom weapons to come

}

-- Create a table of items indexed by name for easy lookup
Items_indexed = {}
for k,v in pairs(Items) do
    Items_indexed[v.name] = v
end