LootItems = 
{
    -- {Item,Rarity,MinQuantity,MaxQuantity}
    [Lootbox.Types.Level1] = 
    {
        ["Bubbles"] = {rarity = 0.011, min = 10, max = 20},
        ["Handgun Ammo"] = {rarity = 0.005, min = 5, max = 10},
        ["Revolver Ammo"] = {rarity = 0.056, min = 2, max = 4},
        ["Sawn-Off Ammo"] = {rarity = 0.047, min = 2, max = 4},
        ["Flares"] = {rarity = 0.094, min = 1, max = 1},
        ["Woet"] = {rarity = 0.028, min = 1, max = 1},
        ["BackTrack"] = {rarity = 0.014, min = 1, max = 1},
        ["Vehicle Repair"] = {rarity = 0.014, min = 1, max = 1},
        ["Vehicle Guard"] = {rarity = 0.009, min = 1, max = 1},
        ["Water"] = {rarity = 0.022, min = 1, max = 1},
        ["Coffee"] = {rarity = 0.056, min = 1, max = 1},
        ["Iced Tea"] = {rarity = 0.045, min = 1, max = 1},
        ["Apple Juice"] = {rarity = 0.03, min = 1, max = 1},
        ["Energy Drink"] = {rarity = 0.025, min = 1, max = 1},
        ["Smoke Grenade"] = {rarity = 0.094, min = 1, max = 1},
        ["Flashbang"] = {rarity = 0.094, min = 1, max = 1},
        ["HE Grenade"] = {rarity = 0.019, min = 1, max = 1},
        ["Chocolate"] = {rarity = 0.07, min = 2, max = 4},
        ["Cookies"] = {rarity = 0.062, min = 2, max = 3},
        ["Peanuts"] = {rarity = 0.037, min = 2, max = 3},
        ["Pretzel"] = {rarity = 0.031, min = 2, max = 3},
        ["Chips"] = {rarity = 0.028, min = 1, max = 2},
        ["Can of Beans"] = {rarity = 0.028, min = 1, max = 1},
        ["Can of Peaches"] = {rarity = 0.028, min = 1, max = 1},
        ["Can of Ham"] = {rarity = 0.028, min = 1, max = 1},
        ["Macadamia Nuts"] = {rarity = 0, min = 1, max = 1},
        ["Lockpick"] = {rarity = 0.006, min = 1, max = 1},
        ["Revolver"] = {rarity = 0.003, min = 1, max = 1},
        ["Bubble Gun"] = {rarity = 0.011, min = 1, max = 1},
        ["Handgun"] = {rarity = 0.002, min = 1, max = 1},
        ["Sawn-Off Shotgun"] = {rarity = 0.002, min = 1, max = 1},
    },
    [Lootbox.Types.Level2] = 
    {
        ["Assault Ammo"] = {rarity = 0.012, min = 6, max = 12},
        ["Bubbles"] = {rarity = 0.014, min = 30, max = 60},
        ["Handgun Ammo"] = {rarity = 0.011, min = 8, max = 16},
        ["Revolver Ammo"] = {rarity = 0.166, min = 3, max = 5},
        ["Sawn-Off Ammo"] = {rarity = 0.086, min = 4, max = 8},
        ["Shotgun Ammo"] = {rarity = 0.028, min = 3, max = 5},
        ["SMG Ammo"] = {rarity = 0.083, min = 10, max = 20},
        ["Helmet"] = {rarity = 0.01, min = 1, max = 1},
        ["Garbage Stash"] = {rarity = 0.001, min = 1, max = 1},
        ["Barrel Stash"] = {rarity = 0.002, min = 1, max = 1},
        ["Battery"] = {rarity = 0.041, min = 1, max = 1},
        ["Bandages"] = {rarity = 0.104, min = 1, max = 2},
        ["BackTrack"] = {rarity = 0.052, min = 1, max = 1},
        ["Vehicle Repair"] = {rarity = 0.052, min = 1, max = 1},
        ["Vehicle Guard"] = {rarity = 0.035, min = 1, max = 1},
        ["CamelBak"] = {rarity = 0.017, min = 1, max = 1},
        ["Mine"] = {rarity = 0.069, min = 1, max = 1},
        ["Toxic Grenade"] = {rarity = 0.058, min = 1, max = 1},
        ["HE Grenade"] = {rarity = 0.069, min = 1, max = 1},
        ["Macadamia Nuts"] = {rarity = 0, min = 1, max = 1},
        ["Lockpick"] = {rarity = 0.01, min = 1, max = 2},
        ["Grapplehook"] = {rarity = 0.003, min = 1, max = 1},
        ["Revolver"] = {rarity = 0.01, min = 1, max = 1},
        ["Bubble Gun"] = {rarity = 0.041, min = 1, max = 1},
        ["Handgun"] = {rarity = 0.009, min = 1, max = 1},
        ["Sawn-Off Shotgun"] = {rarity = 0.007, min = 1, max = 1},
        ["SMG"] = {rarity = 0.004, min = 1, max = 1},
        ["Assault Rifle"] = {rarity = 0.003, min = 1, max = 1},
        ["Shotgun"] = {rarity = 0.003, min = 1, max = 1},
    },
    [Lootbox.Types.Level3] = 
    {
        ["Assault Ammo"] = {rarity = 0.011, min = 30, max = 60},
        ["GrLauncher Ammo"] = {rarity = 0.063, min = 1, max = 2},
        ["Machine Gun Ammo"] = {rarity = 0.085, min = 5, max = 10},
        ["Shotgun Ammo"] = {rarity = 0.068, min = 5, max = 10},
        ["SMG Ammo"] = {rarity = 0.162, min = 25, max = 50},
        ["Sniper Ammo"] = {rarity = 0.041, min = 5, max = 10},
        ["Combat Backpack"] = {rarity = 0.013, min = 1, max = 1},
        ["Explorer Backpack"] = {rarity = 0.013, min = 1, max = 1},
        ["Police Helmet"] = {rarity = 0.034, min = 1, max = 1},
        ["Military Helmet"] = {rarity = 0.017, min = 1, max = 1},
        ["Garbage Stash"] = {rarity = 0.007, min = 1, max = 1},
        ["Barrel Stash"] = {rarity = 0.01, min = 1, max = 1},
        ["Healthpack"] = {rarity = 0.127, min = 1, max = 2},
        ["EVAC"] = {rarity = 0.004, min = 1, max = 1},
        ["Battery"] = {rarity = 0.051, min = 2, max = 4},
        ["Molotov"] = {rarity = 0.113, min = 1, max = 1},
        ["Claymore"] = {rarity = 0.085, min = 1, max = 1},
        ["Macadamia Nuts"] = {rarity = 0, min = 1, max = 1},
        ["Explosives Detector"] = {rarity = 0.02, min = 1, max = 1},
        ["Grapplehook"] = {rarity = 0.013, min = 1, max = 1},
        ["Sniper Rifle"] = {rarity = 0.01, min = 1, max = 1},
        ["SMG"] = {rarity = 0.02, min = 1, max = 1},
        ["Assault Rifle"] = {rarity = 0.017, min = 1, max = 1},
        ["Shotgun"] = {rarity = 0.017, min = 1, max = 1},
    },
    [Lootbox.Types.Level4] = 
    {
        ["GrLauncher Ammo"] = {rarity = 0.104, min = 2, max = 3},
        ["Machine Gun Ammo"] = {rarity = 0.208, min = 5, max = 10},
        ["Rockets"] = {rarity = 0.125, min = 1, max = 2},
        ["Scuba Gear"] = {rarity = 0.01, min = 1, max = 1},
        ["Combat Backpack"] = {rarity = 0.031, min = 1, max = 1},
        ["Explorer Backpack"] = {rarity = 0.031, min = 1, max = 1},
        ["Military Vest"] = {rarity = 0.036, min = 1, max = 1},
        ["Kevlar Vest"] = {rarity = 0.021, min = 1, max = 1},
        ["EVAC"] = {rarity = 0.01, min = 1, max = 1},
        ["Molotov"] = {rarity = 0.278, min = 1, max = 1},
        ["Macadamia Nuts"] = {rarity = 0, min = 1, max = 1},
        ["Explosives Detector"] = {rarity = 0.05, min = 1, max = 1},
        ["Parachute"] = {rarity = 0.01, min = 1, max = 1},
        ["RocketGrapple"] = {rarity = 0.016, min = 1, max = 1},
        ["Sniper Rifle"] = {rarity = 0.025, min = 1, max = 1},
        ["Grenade Launcher"] = {rarity = 0.016, min = 1, max = 1},
        ["Machine Gun"] = {rarity = 0.016, min = 1, max = 1},
        ["Rocket Launcher"] = {rarity = 0.012, min = 1, max = 1},
    },
    [Lootbox.Types.Level5] = 
    {

    },
    [Lootbox.Types.VendingMachineFood] = 
    {
        ["Chocolate"] = {rarity = 0.345, min = 1, max = 2},
        ["Cookies"] = {rarity = 0.23, min = 1, max = 2},
        ["Peanuts"] = {rarity = 0.138, min = 1, max = 2},
        ["Pretzel"] = {rarity = 0.115, min = 1, max = 2},
        ["Chips"] = {rarity = 0.069, min = 1, max = 2},
        ["Can of Beans"] = {rarity = 0.034, min = 1, max = 2},
        ["Can of Peaches"] = {rarity = 0.034, min = 1, max = 2},
        ["Can of Ham"] = {rarity = 0.034, min = 1, max = 2},
        ["Macadamia Nuts"] = {rarity = 0, min = 1, max = 1},
    },
    [Lootbox.Types.VendingMachineDrink] = 
    {
        ["Water"] = {rarity = 0.123, min = 1, max = 2},
        ["Coffee"] = {rarity = 0.307, min = 1, max = 2},
        ["Iced Tea"] = {rarity = 0.246, min = 1, max = 2},
        ["Apple Juice"] = {rarity = 0.164, min = 1, max = 2},
        ["Energy Drink"] = {rarity = 0.136, min = 1, max = 2},
        ["CamelBak"] = {rarity = 0.025, min = 1, max = 2},
    }
    -- FUTURE: NPC loot
}